ARDUINO_DIR       = /Applications/Arduino163.app/Contents/Java
MONITOR_BAUDRATE 	= 115200
MONITOR_PORT      = /dev/cu.usbmodem*
BOARD_TAG         = uno
ARDUINO_LIBS      = Adafruit_NeoPixel Ethernet OSC SPI
AVRDUDE           = /usr/local/bin/avrdude
AVRDUDE_CONF      = /Applications/Arduino163.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf
USER_LIB_PATH     = include
#VARIANT = mega
#F_CPU = 16000000

include  /usr/local/Cellar/arduino-mk/1.5/Arduino.mk
